CLIP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('UserProfile.urls')),
    path('userauthentication/',include('UserAuthentication.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('projects/',include('UserProject.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

UserProject/urls.py
from django.urls import path
from . import views

app_name = 'UserProject'

urlpatterns = [
    path('', views.ProjectList.as_view(), name='project_list'),
    path('view/<slug:slug>', views.ProjectView.as_view(), name='project_view'),
    path('new', views.ProjectCreate.as_view(), name='project_create'),
    path('edit/<slug:slug>', views.ProjectUpdate.as_view(), name='project_edit'),
    path('delete/<slug:slug>', views.ProjectDelete.as_view(), name='project_delete'),

]

UserProject/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Project(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author',
                               help_text='Project creator name')
    collaborators = models.ManyToManyField(User, blank=True , related_name='collaborator')
    observers = models.ManyToManyField(User, blank=True ,  related_name='observers')
    name = models.CharField(max_length=20, help_text='Name of the project')
    short_description = models.CharField(max_length=100, help_text='A one line description for the project', blank=True)
    description = models.TextField(blank=True, help_text='Introduce your project here...')
    logo = models.ImageField(blank=True, help_text='Provide a logo',  upload_to='projectProfile')
    created_date = models.DateField(blank=True, auto_now_add=True)
    end_date = models.DateField()
    skills = models.CharField(max_length=100, blank=True)
    visibility = models.CharField(max_length=1, choices=(
        ('1', 'Public'),
        ('2', 'Restricted'),
        ('3', 'Private')
    ), default=('1', 'Public'), help_text='Control who can see the project. Public => Anyone, '
                                          'Private => Only those invited, '
                                          'Restricted => Like private but people can apply for being an observer or a team member')
    discussion_forum = models.BooleanField(default=False, help_text="Allow discussion forum for general discussions over project")
    public_discussion = models.BooleanField(default=False, help_text='Allow non observers to participate in discussions in the form')
    public_can_vote = models.BooleanField(default=False, help_text='Allow public to vote in the wishlist')
    observer_log_comment = models.BooleanField(default=False, help_text='Allow observers to comment in the logs')
    observer_add_wishlist = models.BooleanField(default=False, help_text='Allow observers to add wish')
    slug = models.SlugField(max_length=50, db_index=True, allow_unicode=False, blank=True, verbose_name='Project URL', unique=True, help_text='Leave blank to autogenerate')

    class Meta:
        permissions = (
        ('can_add_collaborator', 'Can add collaborator'),
        ('can_add_observer', 'Can add observer'),
        )


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('UserProject:project_view', args=[str(self.slug)])

UserProject/forms.py
from django.forms import ModelForm, DateInput
from .models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'logo', 'lic', 'end_date', 'skills']
        widgets = {'end_date':DateInput(attrs={'type':'date'})}

UserProject/views.py
from .models import Project
from django.contrib.auth.models import Group
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.forms import DateInput
from django.urls import reverse
from guardian.shortcuts import assign_perm
from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from .utils import unique_slug_generator

# Create your views here.



class ProjectList( PermissionListMixin, ListView):
    permission_required = 'UserProject.view_project'

    model = Project

class ProjectView( PermissionRequiredMixin, DetailView):
    permission_required = 'UserProject.view_project'
    model = Project

    def get_context_data(self, **kwargs):
        test = self.request.user.has_perm('UserProject.view_project', self.object)
        if (self.request.user.has_perm('UserProject.view_project', self.object)):
            print('has access')
        else:
            print('no access')
        return super().get_context_data(**kwargs)



class ProjectCreate(CreateView):
    model = Project
    fields = ['name', 'short_description', 'description', 'logo', 'end_date', 'skills','visibility','discussion_forum',
              'public_discussion','public_can_vote','observer_log_comment','observer_add_wishlist','slug']
    widgets = {
        'end_date': DateInput(attrs={'type': 'date'})
    }

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['end_date'].widget = DateInput(attrs={'type': 'date'})
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        # If the slug is empty autogenerate a slug
        if form.cleaned_data['slug'].isspace() or not form.cleaned_data['slug']:
            form.instance.slug = unique_slug_generator(form.instance)

        response =   super().form_valid(form)

        ownerGroup,_ = Group.objects.get_or_create(name='ProjectOwner')
        collaboratorGroup, _ = Group.objects.get_or_create(name='ProjectCollaborator')
        observerGroup, _ = Group.objects.get_or_create(name= 'ProjectObserver_' + self.object.slug)

        assign_perm('UserProject.view_project', ownerGroup, self.object)
        assign_perm('UserProject.change_project', ownerGroup, self.object)
        assign_perm('UserProject.delete_project', ownerGroup, self.object)
        assign_perm('UserProject.can_add_collaborator', ownerGroup, self.object)

        assign_perm('UserProject.view_project', collaboratorGroup, self.object)
        assign_perm('UserProject.can_add_observer', ownerGroup, self.object)

        assign_perm('UserProject.view_project', observerGroup, self.object)

        self.request.user.groups.add(ownerGroup)

        return response




class ProjectUpdate(UpdateView):
    model = Project
    fields = ['name', 'short_description', 'description', 'logo', 'end_date', 'skills','visibility','discussion_forum',
              'public_discussion','public_can_vote','observer_log_comment','observer_add_wishlist','slug']

    def get_success_url(self):
            return reverse('UserProject:project_view', kwargs = {'slug':self.object.slug })


    def form_valid(self, form):
        form.instance.author = self.request.user
        # If the slug is empty autogenerate a slug
        if form.cleaned_data['slug'].isspace() or not form.cleaned_data['slug']:
            form.instance.slug = unique_slug_generator(form.instance)

        return  super().form_valid(form)



class ProjectDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'UserProject.delete_project'
    model = Project

    def get_success_url(self):
        return reverse('UserProject:project_list')

UserProject/templates/UserProject/ProjectDash.html
{% extends 'adminlte/base.html'%}
{% block content %}
This is a test
{% endblock content %}

UserProject/templates/UserProject/project_form.html
{% extends 'adminlte/base.html'%}
{% load crispy_forms_tags widget_tweaks static %}

<% endblock %>

{% block page_name %}Create your awesome project here{% endblock %}

{% block content %}
{{ form.non_field_errors }}
<div class="content">
    <div class="box box-primary">
        <form method="post" {% if form.instance.pk %} action="{% url 'UserProject:project_edit' slug=form.instance.slug %}"
              {% else %}
              action="{% url 'UserProject:project_create' %}"
              {% endif %}
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.name.label_tag }}
                            {% render_field form.name class="form-control" %}
                            <div class="small">{{ form.name.help_text }}</div>
                            <div class="small text-danger">{{ form.name.errors }}</div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.slug.label_tag }}
                            {% render_field form.slug class="form-control" %}
                            <div class="small">{{ form.slug.help_text }}</div>
                            <div class="small text-danger">{{ form.slug.errors }}</div>

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ form.logo.label_tag }}
                            {% render_field form.logo class="form-control" %}
                            <div class="small">{{ form.logo.help_text }}</div>
                            <div class="small text-danger">{{ form.logo.errors }}</div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ form.short_description.label_tag }}
                            {% render_field form.short_description class="form-control" %}
                            <div class="small">{{ form.short_description.help_text }}</div>
                            <div class="small text-danger">{{ form.short_description.errors }}</div>
                        </div>

                    </div>
                    <div class="col-md-6">

                        <div class="form-group">
                            {{ form.end_date.label_tag }}
                            {% render_field form.end_date class="form-control" %}
                            <div class="small">{{ form.end_date.help_text }}</div>
                            <div class="small text-danger">{{ form.end_date.errors }}</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ form.skills.label_tag }}
                            {% render_field form.skills class="form-control" %}
                            <div class="small">{{ form.skills.help_text }}</div>
                            <div class="small text-danger">{{ form.skills.errors }}</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ form.visibility.label_tag }}
                            {% render_field form.visibility class="form-control" %}
                            <div class="small">{{ form.visibility.help_text }}</div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{ form.description.label_tag }}
                    {% render_field form.description class="form-control" %}
                    <div class="small">{{ form.description.help_text }}</div>
                    <div class="small text-danger">{{ form.description.errors }}</div>
                </div>

                <h2> Permissions</h2>
                <div class="form-group">
                    {% render_field form.discussion_forum class="form-check-input" %}
                    {{ form.discussion_forum.label_tag }}
                    <div class="small">{{ form.discussion_forum.help_text }}</div>
                </div>
                <h3> Public permissions</h3>
                <div class="form-group">
                    {% render_field form.public_discussion class="form-check-input" %}
                    {{ form.public_discussion.label_tag }}
                    <div class="small">{{ form.public_discussion.help_text }}</div>
                </div>

                <div class="form-group">
                    {% render_field form.public_can_vote class="form-check-input" %}{{ form.public_can_vote.label_tag }}
                    <div class="small">{{ form.public_can_vote.help_text }}</div>
                </div>
                <h3>Observer Permissions</h3>
                <div class="form-group">
                    {% render_field form.observer_log_comment class="form-check-input" %}
                    {{ form.observer_log_comment.label_tag }}
                    <div class="small">{{ form.observer_log_comment.help_text }}</div>
                </div>

                <div class="form-check">
                    {% render_field form.observer_add_wishlist class="form-check-input" %}
                    {{ form.observer_add_wishlist.label_tag }}
                    <div class="small">{{ form.observer_add_wishlist.help_text }}</div>
                </div>
            </div>
            <div class="box-footer">
                {% if form.instance.pk %}
                <input type="submit" value="Update" class="btn btn-primary">
                {% else %}
                <input type="submit" value="Create" class="btn btn-primary">
                {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

UserProject/templates/UserProject/project_list.html
{% extends 'adminlte/base.html'%}
{% load static %}
{% block stylesheets %}

{{ block.super }}
<link href="https://unpkg.com/ionicons@4.4.4/dist/css/ionicons.min.css" rel="stylesheet">
{% endblock %}
{% block page_name %}Projects Dashboard <small>Projects Overview</small>{% endblock %}
{% block content %}


<div class="content-fluid">

    <div class="row">
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Ongoing projects</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'UserProject:project_create' %}"> <span class="label label-warning">Add another project</span></a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
                    <ul class="users-list clearfix">
                        {% for project in object_list|slice:":4" %}
                        <li>
                            {% if project.logo %}
                            <a class="users-list-name" href="{{ project.get_absolute_url }}"> <img src="{{ project.logo.url }}" alt="User Image"></a>
                            {% else %}
                            <a class="users-list-name" href="{{ project.get_absolute_url }}"> <img src="{% static 'Placeholders/fa-book_100px.png' %}" alt="User Image"></a>
                            {% endif %}
                            {{ project.name }}
                            <span class="users-list-date">Today</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <!-- /.users-list -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-center">
                    {% if object_list|length > 4 %}
                    <a href="javascript:void(0)" class="uppercase">View All Projects</a>
                    {% endif %}
                </div>

            </div>
            <!-- /.box-footer -->
        </div>
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">To Do List</h3>

                    <div class="box-tools pull-right">
                        <a href="{% url 'UserProject:project_create' %}"> <span class="label label-warning">Add another project</span></a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
                    <ul class="users-list clearfix">
                        {% for project in object_list|slice:":4" %}
                        <li>
                            {% if project.logo %}
                            <a class="users-list-name" href="{{ project.get_absolute_url }}"> <img src="{{ project.logo.url }}" alt="User Image"></a>
                            {% else %}
                            <a class="users-list-name" href="{{ project.get_absolute_url }}"> <img src="{% static 'Placeholders/fa-book_100px.png' %}" alt="User Image"></a>
                            {% endif %}                            {{ project.name }}
                            <span class="users-list-date">Today</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <!-- /.users-list -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-center">
                    {% if object_list|length > 4 %}
                    <a href="javascript:void(0)" class="uppercase">View All Projects</a>
                    {% endif %}
                </div>

            </div>
            <!-- /.box-footer -->
        </div>
    </div>
</div>
{% endblock content %}