CLIP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('UserProfile.urls')),
    path('userauthentication/',include('UserAuthentication.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('projects/',include('UserProject.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

UserProfile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'UserProfile'

urlpatterns = [
    path('', views.showProfile.as_view(), name='profile'),
]

UserProject/urls.py
from django.urls import path
from . import views

app_name = 'UserProject'

urlpatterns = [
    path('', views.ProjectList.as_view(), name='project_list'),
    path('view/<slug:slug>', views.ProjectView.as_view(), name='project_view'),
    path('new', views.ProjectCreate.as_view(), name='project_create'),
    path('edit/<slug:slug>', views.ProjectUpdate.as_view(), name='project_edit'),
    path('delete/<slug:slug>', views.ProjectDelete.as_view(), name='project_delete'),

]

UserProfile/models.py
from django.db import models

# Create your models here.

UserProfile/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from allauth.socialaccount.models import SocialAccount

# Create your views here.
class showProfile(LoginRequiredMixin, TemplateView):
    template_name = 'UserProfile/profile.html'
    def get_context_data(self):
        context={'user':self.request.user}
        return context

UserProfile/templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}
{% load adminlte_helpers i18n %}

{% block logo_text %}<b>CLIP</b>{% endblock %}
{% block logo_text_small %}<b>CLIP</b>{% endblock %}
{% block change_password_url %}{% url 'account_change_password' %}{% endblock %}



{% block header_dropdowns %}
{% if request.user.is_authenticated %}
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        {% if user.socialaccount_set.all|length != 0 %}
        <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" height="20" class="img-circle" alt="User Image">
        {% else %}
        <img src="{% avatar_url size=20 %}" class="img-circle" alt="User Image">
        {% endif %}
        <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
    </a>
    <ul class="dropdown-menu">
        {% block user_header %}
        <li class="user-header">
            {% if user.socialaccount_set.all|length != 0 %}
            <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" height="20" class="img-circle" alt="User Image">
            {% else %}
            <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
            {% endif %}
            <p>
                {% firstof request.user.get_short_name request.user.get_username %}
                <small>Member since {{ request.user.date_joined }}</small>
            </p>
        </li>
        {% endblock %}

        <!-- Menu Footer-->
        {% block menu_footer %}
        <li class="user-footer">
            <div class="pull-left">
                <a href="{% url 'account_change_password' %}"
                   class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
            </div>
            <div class="pull-right">
                <form action="{% logout_url %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Sign out" class="btn btn-default btn-flat">
                </form>
            </div>
        </li>
        {% endblock %}

    </ul>
</li>
{% endif %}
{% endblock header_dropdowns %}

UserProfile/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}
{% load adminlte_helpers %}

{% block user_panel %}
<div class="user-panel">
    <div class="pull-left image">
        {% if user.socialaccount_set.all|length != 0 %}
        <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" class="img-circle" alt="User Image">
        {% else %}
        <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
        {% endif %}
    </div>
    <div class="pull-left info">
        <p>{% firstof request.user.get_full_name request.user.username %}</p>
    </div>
</div>
{% endblock %}

{% block nav_links %}
<li>
    <a href="{% url 'UserProject:project_list' %}">
        <i class="fa fa-book"></i> <span>Projects</span>
    </a>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-group"></i> <span>Sub menu</span>
        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
    </a>
    <ul class="treeview-menu">
        <li>
            <a href="#">
                <i class="fa fa-user"></i> Another link
            </a>
        </li>
    </ul>
</li>
{% endblock nav_links %}